// Industry catalog used by the qualification prompt to bootstrap a user's
// folder structure. Selecting an industry calls saveCustomRooms() with the
// matching `folders` list; the user can still edit them later via Settings.
//
// `icon` is an Ionicons name used in the selection grid. `folders` is the
// pre-loaded set of rooms (id, name, icon emoji). Folder counts >10 are
// allowed here because saveCustomRooms has no cap — the in-app RoomEditor
// only caps user-driven additions, not the seed list.

const room = (name, icon = '📁') => ({
  id: `seed_${name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')}`,
  name,
  icon,
});

export const INDUSTRIES = [
  {
    id: 'cleaning',
    icon: 'sparkles-outline',
    labelKey: 'qualification.cleaning',
    defaultLabel: 'Cleaning Services',
    folders: [
      room('Kitchen', '🍳'),
      room('Bathroom', '🛁'),
      room('Bedroom', '🛏️'),
      room('Living Room', '🛋️'),
      room('Dining Room', '🍽️'),
      room('Hallway', '🚪'),
      room('Office', '💼'),
      room('Basement', '🏚️'),
      room('Laundry Room', '🧺'),
      room('Windows', '🪟'),
      room('Floors', '🪵'),
      room('Garage', '🚗'),
    ],
  },
  {
    id: 'contractors',
    icon: 'construct-outline',
    labelKey: 'qualification.contractors',
    defaultLabel: 'General Contractors / Remodeling',
    folders: [
      room('Kitchen Remodel', '🍳'),
      room('Bathroom Remodel', '🛁'),
      room('Living Room', '🛋️'),
      room('Basement', '🏚️'),
      room('Exterior', '🏠'),
      room('Roof', '🏠'),
      room('Deck', '🪵'),
      room('Garage', '🚗'),
      room('Flooring', '🪵'),
      room('Drywall', '🧱'),
      room('Plumbing', '🚰'),
      room('Electrical', '⚡'),
    ],
  },
  {
    id: 'handyman',
    icon: 'hammer-outline',
    labelKey: 'qualification.handyman',
    defaultLabel: 'Handyman / Repair',
    folders: [
      room('Wall Repair', '🧱'),
      room('Ceiling Repair', '🔼'),
      room('Door Repair', '🚪'),
      room('Window Repair', '🪟'),
      room('Plumbing Repair', '🔧'),
      room('Electrical Repair', '⚡'),
      room('Flooring Repair', '🪵'),
      room('Cabinet Repair', '🗄️'),
      room('Exterior Repair', '🏠'),
      room('Fence Repair', '🚧'),
    ],
  },
  {
    id: 'roofing',
    icon: 'home-outline',
    labelKey: 'qualification.roofing',
    defaultLabel: 'Roofing',
    folders: [
      room('Front Roof', '🏠'),
      room('Back Roof', '🏠'),
      room('Gutters', '🌧️'),
      room('Chimney', '🏚️'),
      room('Flashing', '⚡'),
      room('Skylights', '☀️'),
      room('Attic', '🏚️'),
      room('Siding', '🧱'),
    ],
  },
  {
    id: 'landscaping',
    icon: 'leaf-outline',
    labelKey: 'qualification.landscaping',
    defaultLabel: 'Landscaping',
    folders: [
      room('Front Yard', '🌳'),
      room('Backyard', '🌿'),
      room('Lawn', '🌱'),
      room('Garden Beds', '🌷'),
      room('Trees', '🌳'),
      room('Patio', '🪨'),
      room('Driveway', '🚗'),
      room('Fence', '🚧'),
      room('Irrigation', '💧'),
      room('Walkway', '🛤️'),
    ],
  },
  {
    id: 'pressure_washing',
    icon: 'rainy-outline',
    labelKey: 'qualification.pressureWashing',
    defaultLabel: 'Pressure Washing',
    folders: [
      room('Driveway', '🚗'),
      room('Siding', '🧱'),
      room('Deck', '🪵'),
      room('Patio', '🪨'),
      room('Roof', '🏠'),
      room('Fence', '🚧'),
      room('Sidewalk', '🛤️'),
      room('Garage Door', '🚪'),
    ],
  },
  {
    id: 'flooring',
    icon: 'grid-outline',
    labelKey: 'qualification.flooring',
    defaultLabel: 'Flooring',
    folders: [
      room('Living Room Floor', '🛋️'),
      room('Kitchen Floor', '🍳'),
      room('Bathroom Floor', '🛁'),
      room('Bedroom Floor', '🛏️'),
      room('Stairs', '🪜'),
      room('Hallway', '🚪'),
      room('Tile Area', '🟫'),
      room('Hardwood Area', '🪵'),
    ],
  },
  {
    id: 'painting',
    icon: 'color-palette-outline',
    labelKey: 'qualification.painting',
    defaultLabel: 'Painting',
    folders: [
      room('Walls', '🧱'),
      room('Ceiling', '🔼'),
      room('Trim', '📏'),
      room('Doors', '🚪'),
      room('Cabinets', '🗄️'),
      room('Exterior Walls', '🏠'),
      room('Fence', '🚧'),
      room('Deck', '🪵'),
    ],
  },
  {
    id: 'plumbing',
    icon: 'water-outline',
    labelKey: 'qualification.plumbing',
    defaultLabel: 'Plumbing',
    folders: [
      room('Kitchen Sink', '🚰'),
      room('Bathroom Sink', '🚰'),
      room('Shower', '🚿'),
      room('Bathtub', '🛁'),
      room('Toilet', '🚽'),
      room('Water Heater', '🔥'),
      room('Pipes', '🚰'),
      room('Drain System', '💧'),
    ],
  },
  {
    id: 'electrical',
    icon: 'flash-outline',
    labelKey: 'qualification.electrical',
    defaultLabel: 'Electrical',
    folders: [
      room('Electrical Panel', '⚡'),
      room('Lighting', '💡'),
      room('Ceiling Fans', '🌀'),
      room('Outlets', '🔌'),
      room('Switches', '🔘'),
      room('Wiring', '⚡'),
      room('Exterior Lighting', '💡'),
    ],
  },
  {
    id: 'hvac',
    icon: 'thermometer-outline',
    labelKey: 'qualification.hvac',
    defaultLabel: 'HVAC',
    folders: [
      room('Furnace', '🔥'),
      room('AC Unit', '❄️'),
      room('Ductwork', '🌬️'),
      room('Thermostat', '🌡️'),
      room('Air Vents', '🌬️'),
      room('Filters', '🔲'),
      room('Utility Room', '🔧'),
    ],
  },
  {
    id: 'auto_detailing',
    icon: 'car-outline',
    labelKey: 'qualification.autoDetailing',
    defaultLabel: 'Auto Detailing',
    folders: [
      room('Exterior', '🚗'),
      room('Interior', '🚗'),
      room('Seats', '💺'),
      room('Dashboard', '📋'),
      room('Trunk', '🎒'),
      room('Engine Bay', '⚙️'),
      room('Wheels', '🛞'),
      room('Headlights', '💡'),
    ],
  },
  {
    id: 'beauty',
    icon: 'cut-outline',
    labelKey: 'qualification.beauty',
    defaultLabel: 'Beauty Salon / Hair',
    folders: [
      room('Hair Color', '🎨'),
      room('Haircut', '✂️'),
      room('Styling', '💆'),
      room('Extensions', '💁'),
      room('Brows', '👁️'),
      room('Lashes', '👁️'),
      room('Nails', '💅'),
      room('Makeup', '💄'),
    ],
  },
  {
    id: 'med_spa',
    icon: 'medical-outline',
    labelKey: 'qualification.medSpa',
    defaultLabel: 'Med Spa / Aesthetics',
    folders: [
      room('Face', '😊'),
      room('Lips', '💋'),
      room('Jawline', '😐'),
      room('Skin Treatment', '✨'),
      room('Acne', '⚪'),
      room('Laser Area', '🔆'),
      room('Body Contouring', '🧍'),
    ],
  },
  {
    id: 'pest_control',
    icon: 'bug-outline',
    labelKey: 'qualification.pestControl',
    defaultLabel: 'Pest Control',
    folders: [
      room('Kitchen', '🍳'),
      room('Basement', '🏚️'),
      room('Attic', '🏚️'),
      room('Exterior', '🏠'),
      room('Garage', '🚗'),
      room('Crawl Space', '🏚️'),
      room('Entry Points', '🚪'),
    ],
  },
  {
    id: 'restoration',
    icon: 'refresh-outline',
    labelKey: 'qualification.restoration',
    defaultLabel: 'Restoration / Water Damage',
    folders: [
      room('Kitchen', '🍳'),
      room('Bathroom', '🛁'),
      room('Basement', '🏚️'),
      room('Ceiling', '🔼'),
      room('Walls', '🧱'),
      room('Flooring', '🪵'),
      room('Mold Area', '🦠'),
      room('Exterior Damage', '🏚️'),
    ],
  },
  {
    id: 'junk_removal',
    icon: 'trash-outline',
    labelKey: 'qualification.junkRemoval',
    defaultLabel: 'Junk Removal',
    folders: [
      room('Garage', '🚗'),
      room('Basement', '🏚️'),
      room('Backyard', '🌿'),
      room('Storage Room', '📦'),
      room('Office', '💼'),
      room('Attic', '🏚️'),
      room('Construction Debris', '🪨'),
    ],
  },
  {
    id: 'property_management',
    icon: 'business-outline',
    labelKey: 'qualification.propertyManagement',
    defaultLabel: 'Property Management / Realtors',
    folders: [
      room('Kitchen', '🍳'),
      room('Bathroom', '🛁'),
      room('Living Room', '🛋️'),
      room('Bedroom', '🛏️'),
      room('Exterior', '🏠'),
      room('Garage', '🚗'),
      room('Balcony', '🌇'),
      room('Common Areas', '🏛️'),
    ],
  },
  {
    id: 'other',
    icon: 'ellipsis-horizontal-outline',
    labelKey: 'qualification.other',
    defaultLabel: 'Other',
    folders: [
      room('Section 1'),
      room('Section 2'),
      room('Section 3'),
      room('Section 4'),
      room('Section 5'),
    ],
  },
];

export const getIndustryById = (id) => INDUSTRIES.find((i) => i.id === id);
